-- :fennel:1664321968
local function keymap(mode, lhs, rhs)
  _G.assert((nil ~= rhs), "Missing argument rhs on keymaps.fnl:1")
  _G.assert((nil ~= lhs), "Missing argument lhs on keymaps.fnl:1")
  _G.assert((nil ~= mode), "Missing argument mode on keymaps.fnl:1")
  return vim.api.nvim_set_keymap(mode, lhs, rhs, {noremap = true, silent = true})
end
keymap("i", "jk", "<ESC>")
keymap("i", "<M-#>", "#")
keymap("n", "<C-l>", "20zl")
keymap("n", "<C-h>", "20zh")
keymap("", "<Space>", "<Nop>")
vim.g.mapleader = " "
vim.g.localleader = " "
keymap("n", "<C-j>", "<PageDown>zz")
keymap("n", "<C-k>", "<PageUp>zz")
keymap("n", "<leader>vv", ":e ~/dotfiles/nvim<CR>")
keymap("n", "<leader>vs", ":PackerSync<CR>")
keymap("n", "<leader>vi", ":PackerInstall<CR>")
keymap("n", "<leader>vv", "<S-v>")
keymap("n", "<leader>da", ":e ~/dotfiles/alacritty/alacritty.yml<CR>")
keymap("n", "<leader>p", ":Prettier<CR>")
keymap("n", "<leader>wl", "<C-w>l")
keymap("n", "<leader>wh", "<C-w>h")
keymap("n", "<leader>wj", "<C-w>j")
keymap("n", "<leader>wk", "<C-w>k")
keymap("n", "<leader>wv", ":vs<CR>")
keymap("n", "<leader>wq", ":exit<CR>")
keymap("n", "<leader>q", ":qa!<CR>")
vim.cmd("vnoremap <silent> <leader>y \"+y\"")
keymap("", "f", "<Plug>Sneak_s")
return keymap("", "F", "<Plug>Sneak_S")