-- :fennel:1664319254
local function option(name, value)
  return vim.api.nvim_set_option(name, value)
end
vim.cmd("set nowrap!")
option("syntax", "on")
option("termguicolors", true)
vim.cmd("colorscheme tokyonight-night")
option("relativenumber", true)
option("rnu", true)
option("number", true)
option("shiftwidth", 2)
option("autoindent", true)
option("smartindent", true)
option("tabstop", 2)
option("softtabstop", 2)
option("smarttab", true)
return option("mouse", "a")